/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EchoRouteImport } from './routes/echo'
import { Route as HolterRouteImport } from './routes/holter'
import { Route as StressTestRouteImport } from './routes/stress-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoRoute = EchoRouteImport.update({
  id: '/echo',
  path: '/echo',
  getParentRoute: () => rootRouteImport,
} as any)
const HolterRoute = HolterRouteImport.update({
  id: '/holter',
  path: '/holter',
  getParentRoute: () => rootRouteImport,
} as any)
const StressTestRoute = StressTestRouteImport.update({
  id: '/stress-test',
  path: '/stress-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/echo': typeof EchoRoute
  '/holter': typeof HolterRoute
  '/stress-test': typeof StressTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/echo': typeof EchoRoute
  '/holter': typeof HolterRoute
  '/stress-test': typeof StressTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/echo': typeof EchoRoute
  '/holter': typeof HolterRoute
  '/stress-test': typeof StressTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/echo' | '/holter' | '/stress-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/echo' | '/holter' | '/stress-test'
  id: '__root__' | '/' | '/echo' | '/holter' | '/stress-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EchoRoute: typeof EchoRoute
  HolterRoute: typeof HolterRoute
  StressTestRoute: typeof StressTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echo': {
      id: '/echo'
      path: '/echo'
      fullPath: '/echo'
      preLoaderRoute: typeof EchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holter': {
      id: '/holter'
      path: '/holter'
      fullPath: '/holter'
      preLoaderRoute: typeof HolterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress-test': {
      id: '/stress-test'
      path: '/stress-test'
      fullPath: '/stress-test'
      preLoaderRoute: typeof StressTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EchoRoute: EchoRoute,
  HolterRoute: HolterRoute,
  StressTestRoute: StressTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
