/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EchocardiogramRouteImport } from './routes/echocardiogram'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StockTakeRouteImport } from './routes/stock-take'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EchocardiogramRoute = EchocardiogramRouteImport.update({
  id: '/echocardiogram',
  path: '/echocardiogram',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakeRoute = StockTakeRouteImport.update({
  id: '/stock-take',
  path: '/stock-take',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/echocardiogram': typeof EchocardiogramRoute
  '/staff': typeof StaffRoute
  '/stock-take': typeof StockTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/echocardiogram': typeof EchocardiogramRoute
  '/staff': typeof StaffRoute
  '/stock-take': typeof StockTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/echocardiogram': typeof EchocardiogramRoute
  '/staff': typeof StaffRoute
  '/stock-take': typeof StockTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/echocardiogram' | '/staff' | '/stock-take'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/echocardiogram' | '/staff' | '/stock-take'
  id: '__root__' | '/' | '/echocardiogram' | '/staff' | '/stock-take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EchocardiogramRoute: typeof EchocardiogramRoute
  StaffRoute: typeof StaffRoute
  StockTakeRoute: typeof StockTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echocardiogram': {
      id: '/echocardiogram'
      path: '/echocardiogram'
      fullPath: '/echocardiogram'
      preLoaderRoute: typeof EchocardiogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-take': {
      id: '/stock-take'
      path: '/stock-take'
      fullPath: '/stock-take'
      preLoaderRoute: typeof StockTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EchocardiogramRoute: EchocardiogramRoute,
  StaffRoute: StaffRoute,
  StockTakeRoute: StockTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
