/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminFacilitiesRouteImport } from './routes/admin-facilities'
import { Route as BloodPressureRouteImport } from './routes/blood-pressure'
import { Route as EchoRouteImport } from './routes/echo'
import { Route as HolterRouteImport } from './routes/holter'
import { Route as LungFunctionRouteImport } from './routes/lung-function'
import { Route as OutsourceRouteImport } from './routes/outsource'
import { Route as RheumatologyRouteImport } from './routes/rheumatology'
import { Route as StressTestRouteImport } from './routes/stress-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/admin-facilities',
  path: '/admin-facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodPressureRoute = BloodPressureRouteImport.update({
  id: '/blood-pressure',
  path: '/blood-pressure',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoRoute = EchoRouteImport.update({
  id: '/echo',
  path: '/echo',
  getParentRoute: () => rootRouteImport,
} as any)
const HolterRoute = HolterRouteImport.update({
  id: '/holter',
  path: '/holter',
  getParentRoute: () => rootRouteImport,
} as any)
const LungFunctionRoute = LungFunctionRouteImport.update({
  id: '/lung-function',
  path: '/lung-function',
  getParentRoute: () => rootRouteImport,
} as any)
const OutsourceRoute = OutsourceRouteImport.update({
  id: '/outsource',
  path: '/outsource',
  getParentRoute: () => rootRouteImport,
} as any)
const RheumatologyRoute = RheumatologyRouteImport.update({
  id: '/rheumatology',
  path: '/rheumatology',
  getParentRoute: () => rootRouteImport,
} as any)
const StressTestRoute = StressTestRouteImport.update({
  id: '/stress-test',
  path: '/stress-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-facilities': typeof AdminFacilitiesRoute
  '/blood-pressure': typeof BloodPressureRoute
  '/echo': typeof EchoRoute
  '/holter': typeof HolterRoute
  '/lung-function': typeof LungFunctionRoute
  '/outsource': typeof OutsourceRoute
  '/rheumatology': typeof RheumatologyRoute
  '/stress-test': typeof StressTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-facilities': typeof AdminFacilitiesRoute
  '/blood-pressure': typeof BloodPressureRoute
  '/echo': typeof EchoRoute
  '/holter': typeof HolterRoute
  '/lung-function': typeof LungFunctionRoute
  '/outsource': typeof OutsourceRoute
  '/rheumatology': typeof RheumatologyRoute
  '/stress-test': typeof StressTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-facilities': typeof AdminFacilitiesRoute
  '/blood-pressure': typeof BloodPressureRoute
  '/echo': typeof EchoRoute
  '/holter': typeof HolterRoute
  '/lung-function': typeof LungFunctionRoute
  '/outsource': typeof OutsourceRoute
  '/rheumatology': typeof RheumatologyRoute
  '/stress-test': typeof StressTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-facilities'
    | '/blood-pressure'
    | '/echo'
    | '/holter'
    | '/lung-function'
    | '/outsource'
    | '/rheumatology'
    | '/stress-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-facilities'
    | '/blood-pressure'
    | '/echo'
    | '/holter'
    | '/lung-function'
    | '/outsource'
    | '/rheumatology'
    | '/stress-test'
  id:
    | '__root__'
    | '/'
    | '/admin-facilities'
    | '/blood-pressure'
    | '/echo'
    | '/holter'
    | '/lung-function'
    | '/outsource'
    | '/rheumatology'
    | '/stress-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  BloodPressureRoute: typeof BloodPressureRoute
  EchoRoute: typeof EchoRoute
  HolterRoute: typeof HolterRoute
  LungFunctionRoute: typeof LungFunctionRoute
  OutsourceRoute: typeof OutsourceRoute
  RheumatologyRoute: typeof RheumatologyRoute
  StressTestRoute: typeof StressTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-facilities': {
      id: '/admin-facilities'
      path: '/admin-facilities'
      fullPath: '/admin-facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-pressure': {
      id: '/blood-pressure'
      path: '/blood-pressure'
      fullPath: '/blood-pressure'
      preLoaderRoute: typeof BloodPressureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echo': {
      id: '/echo'
      path: '/echo'
      fullPath: '/echo'
      preLoaderRoute: typeof EchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holter': {
      id: '/holter'
      path: '/holter'
      fullPath: '/holter'
      preLoaderRoute: typeof HolterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lung-function': {
      id: '/lung-function'
      path: '/lung-function'
      fullPath: '/lung-function'
      preLoaderRoute: typeof LungFunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outsource': {
      id: '/outsource'
      path: '/outsource'
      fullPath: '/outsource'
      preLoaderRoute: typeof OutsourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rheumatology': {
      id: '/rheumatology'
      path: '/rheumatology'
      fullPath: '/rheumatology'
      preLoaderRoute: typeof RheumatologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress-test': {
      id: '/stress-test'
      path: '/stress-test'
      fullPath: '/stress-test'
      preLoaderRoute: typeof StressTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  BloodPressureRoute: BloodPressureRoute,
  EchoRoute: EchoRoute,
  HolterRoute: HolterRoute,
  LungFunctionRoute: LungFunctionRoute,
  OutsourceRoute: OutsourceRoute,
  RheumatologyRoute: RheumatologyRoute,
  StressTestRoute: StressTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
